sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '10'
  - '12'
before_script:
  - npm install
  - npm prune
  - npm run lint
  - npm run test
after_success: npm run coverage
branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
